export type Lang = "uk" | "en";

export const STRINGS = {
  uk: {
    navLabels: [
      "01 / INTRO",
      "02 / ПОСЛУГИ",
      "03 / ДО / ПІСЛЯ",
      "04 / КОМАНДА",
      "05 / ВІДГУКИ",
      "06 / ТІКТОК",
      "07 / КЛІНІКА",
      "08 / АДРЕСА",
      "09 / КОНТАКТ",
    ],
    marquee: [
      "НЕВІДКЛАДНА ДОПОМОГА",
      "КОСМЕТИЧНА СТОМАТОЛОГІЯ",
      "ВІДБІЛЮВАННЯ",
      "ІМПЛАНТИ",
      "ЕЛАЙНЕРИ",
      "ВІНІРИ",
      "КОРЕНЕВІ КАНАЛИ",
      "ОРТОДОНТІЯ",
      "ІМПЛАНТАЦІЯ",
    ],
    hero: {
      lines: ["ТВОЯ", "ПОСМІШКА.", "ТВОЇ ПРАВИЛА."],
      sub: "Без нотацій. Без осуду. Просто якісна допомога — і справді хороша кава.",
      cta: "Записатись безкоштовно →",
      stats: [
        ["2400+", "Щасливих посмішок"],
        ["98%", "Повертаються знову"],
        ["4.9", "Google рейтинг"],
      ] as [string, string][],
    },
    services: {
      lines: ["ВИПРАВ.", "ВИРІВНЯЙ.", "ЗАБЛИЩИ."],
      sub: "Все що потрібно твоїй посмішці — в одному місці.",
      hint: "Натисни на картку — дивись ціни",
      toggleOpen: "▲ згорнути",
      toggleClosed: "▼ ціни",
      panelFoot:
        "Точну вартість уточнює лікар на консультації — вона безкоштовна",
      list: [
        { num: "01", name: "Вінири", desc: "Художня реставрація та керамічні вінири E-max.", price: "від 3 500 грн", items: [
          { name: "Композитні вінири без нанесення", price: "3 500 грн" },
          { name: "Композитні вінири з нанесенням", price: "100$" },
          { name: "Керамічні вінири E-max", price: "10 500 грн" },
          { name: "Керамічні вінири E-max Преміум", price: "12 000 грн" },
        ] },
        { num: "02", name: "Ортопедична", desc: "Коронки, протезування, вінири та зняття відбитків.", price: "від 700 грн", items: [
          { name: "Металокерамічна коронка", price: "5 000 грн" },
          { name: "Керамічна коронка (цирконій)", price: "8 000–10 000 грн" },
          { name: "Керамічний вінір (EMAX)", price: "10 500–12 000 грн" },
          { name: "Знімне протезування", price: "18 000–25 000 грн" },
          { name: "Зняття відбитків", price: "1 000 грн" },
          { name: "Зняття сканів", price: "2 000 грн" },
          { name: "Модель (половина щелепи)", price: "1 000 грн" },
          { name: "Модель (вся щелепа)", price: "2 000 грн" },
          { name: "Цементування зовнішньої коронки (1 од.)", price: "700 грн" },
          { name: "Цементування зовнішньої коронки (2 од.)", price: "1 200 грн" },
          { name: "Зняття коронки (за одну)", price: "700 грн" },
        ] },
        { num: "03", name: "Елайнери", desc: "Ніхто не помітить. Ти — відчуєш.", price: "від 25 000 грн", items: [
          { name: "Елайнери (повний курс)", price: "від 25 000 грн" },
          { name: "Брекет-система", price: "від 18 000 грн" },
          { name: "Ретейнери", price: "від 2 400 грн" },
        ] },
        { num: "04", name: "Відбілювання", desc: "Чистка та відбілювання — домашні та кабінетні методи.", price: "від 2 000 грн", items: [
          { name: "Професійна чистка зубів", price: "2 000–2 500 грн" },
          { name: "Відбілювання за одне відвідування", price: "4 000 грн" },
          { name: "Чистка + відбілювання", price: "5 500 грн" },
          { name: "Відбілювання капами на 2 тижні", price: "7 700 грн" },
          { name: "Відбілювання капами на 4 тижні", price: "10 400 грн" },
        ] },
        { num: "05", name: "Огляд", desc: "Консультація, анестезія, пломбування, лікування каналів.", price: "від 200 грн", items: [
          { name: "Консультація", price: "500 грн" },
          { name: "Консультація онлайн", price: "500 грн" },
          { name: "Анестезія", price: "200 грн" },
          { name: "Коффердам", price: "200 грн" },
          { name: "Оптрагейт (роторозширювач)", price: "200 грн" },
          { name: "Тимчасова пломба", price: "300 грн" },
          { name: "Пломба (Японія/США) — середній каріс", price: "2 300 грн" },
          { name: "Пломба (Японія/США) — глибокий каріс", price: "2 500 грн" },
          { name: "Лікування кореневих каналів (за один канал)", price: "1 200–1 500 грн" },
          { name: "Зняття гострого болю (пульпіт, пародонтит)", price: "1 200 грн" },
        ] },
        { num: "06", name: "Терміново", desc: "Зламаний зуб? Того ж дня.", price: "Телефонуй", items: [
          { name: "Огляд при болю", price: "Безкоштовно" },
          { name: "Видалення зуба", price: "від 1 200 грн" },
          { name: "Тимчасова пломба", price: "від 600 грн" },
        ] },
      ],
    },
    beforeAfter: {
      lines: ["ПЕРЕТЯГНИ.", "ПОБАЧ.", "ПОВІР."],
      sub: "Реальні до/після. Реальні пацієнти. Кожен випадок — правда.",
      casesHint: "кейси · перетягни повзунок",
      cases: [
        { treatment: "8 вінірів", duration: "2 тижні", before: "Криві, потемнілі зуби", after: "Порцелянові вініри — природна білість" },
        { treatment: "Один імплант", duration: "3 місяці", before: "Відсутній передній зуб", after: "Імплант із керамічною коронкою" },
        { treatment: "Zoom-відбіл", duration: "1 сеанс", before: "Жовте забарвлення", after: "Яскравий рівномірний відтінок" },
      ],
    },
    team: {
      eyebrow: "НАША КОМАНДА",
      lines: ["НЕ СТОМАТОЛОГ", "ТВОЇХ БАТЬКІВ."],
      members: [
        { name: "Д-р Чиркова", title: "Лікар-стоматолог · Косметична та реставраційна стоматологія", years: 14, yearsLabel: "РОКІВ ПРАКТИКИ", bio: "Я відкрила клініку з однією метою: щоб пацієнти почувались дійсно почутими — а не просто зубом у конвеєрі. Кожна усмішка — це унікальна історія." },
        { name: "Д-р Мельник", title: "Ортодонт · Елайнери та брекет-системи", years: 9, yearsLabel: "РОКІВ ПРАКТИКИ", bio: "Спеціалізується на ортодонтичному лікуванні з використанням сучасних елайнерів та цифрового планування. Понад 800 завершених ортодонтичних випадків." },
      ],
    },
    reviews: {
      lines: ["ВОНИ СКАЗАЛИ.", "НЕ МИ."],
      sub: "Реальні слова. Без фільтрів.",
      list: [
        { initials: "МВ", name: "Марія В.", age: "з 2026", text: "Найкраща клініка у Дніпрі! Вінири зробили за 2 тижні — результат вище очікувань." },
        { initials: "ДК", name: "Дмитро К.", age: "з 2026", text: "Лікар уважний і не поспішає. Вперше не боявся йти до стоматолога!" },
        { initials: "ІС", name: "Ірина С.", age: "з 2026", text: "Зробили імплант — навіть забула де він. Дякую всій команді за увагу та підтримку!" },
        { initials: "АК", name: "Аліна К.", age: "з 2021", text: "Чудовий сервіс — все швидко, без болю і нотацій. Тепер не переживаю за посмішку." },
        { initials: "МД", name: "Максим Д.", age: "з 2020", text: "Зламав зуб — все зробили швидко, акуратно і без зайвих слів. Рекомендую." },
        { initials: "ОС", name: "Олена С.", age: "з 2022", text: "Тріщину на зубі прибрали за один візит. Тепер можу їсти навіть горішки." },
      ],
    },
    tiktok: {
      tt: {
        brand: "TikTok",
        lines: ["ДИВИСЬ.", "ЯК МИ", "ЖИВЕМО."],
        sub: "Реальне життя клініки без постановок і фільтрів — підписуйся.",
        stats: [["6 800+", "Підписників"], ["249", "Відео"]] as [string, string][],
        videos: [
          { id: "7643038472294386965", caption: "Half Price у Дніпрі" },
          { id: "7584496719946173708", caption: "Пацієнт незадоволений 😳" },
        ],
      },
      ig: {
        brand: "Instagram",
        lines: ["ПІДПИШИСЬ.", "ТА.", "ДИВИСЬ."],
        sub: "Щоденне життя клініки, результати, команда — все тут.",
        stats: [["6 800+", "Підписників"], ["249", "Публікацій"]] as [string, string][],
        posts: [
          { id: "DWeVhTFDYC3", caption: "Zoom відбілювання — 8 тонів за 1 сеанс ✨" },
          { id: "DYFoSO5tuGD", caption: "Вініри за 2 тижні — кастомний фарфор 🦷" },
        ],
      },
    },
    clinic: {
      lines: ["ПРОСТІР.", "В ЯКОМУ", "НЕ СТРАШНО."],
      sub: "Сучасне обладнання. Затишна атмосфера. Без стресу.",
      videoLabel: "Відео клініки",
      stats: [
        { num: "200м²", label: "сучасного простору" },
        { num: "5", label: "обладнаних кабінетів" },
        { num: "2021", label: "рік відкриття" },
      ],
      photos: ["Зал очікування", "Кабінет 1", "Кабінет 2", "Стерилізація"],
    },
    location: {
      lines: ["ЗНАЙДИ.", "ПРИХОДЬ.", "ВІДЧУЙ."],
      sub: "Ми в центрі Дніпра. Поруч — метро, паркінг, кава після прийому.",
      contacts: [
        { label: "Телефон", val: "+38 (056) 123-45-67" },
        { label: "Адреса", val: "вул. Михайла Грушевського, 16, Дніпро" },
        { label: "Графік", val: "Пн–Пт 9:00–20:00 · Сб 10:00–18:00" },
      ],
      reviewsTitle: "GOOGLE ВІДГУКИ",
      googleReviews: [
        { name: "Марія В.", text: "Найкраща клініка у Дніпрі! Вініри зробили за 2 тижні — результат вище очікувань.", ago: "2 тижні тому" },
        { name: "Дмитро К.", text: "Лікар уважний і не поспішає. Вперше не боявся йти до стоматолога!", ago: "1 місяць тому" },
        { name: "Ірина С.", text: "Зробили імплант — навіть забула де він. Дякую всій команді за увагу та підтримку!", ago: "2 місяці тому" },
      ],
    },
    contact: {
      lines: ["ДОСИТЬ", "ДУМАТИ.", "ПОЧИНАЙ."],
      sub: "Перша консультація — безкоштовно. Відповідь за 2 години.",
      eyebrow: "ШВИДКИЙ ЗАПИТ",
      labels: { name: "Ваше ім'я", phone: "Телефон *", service: "Послуга", via: "Зручний зв'язок", note: "Примітка (за бажанням)" },
      placeholders: { name: "Катерина", phone: "+380 __ ___-__-__", note: "Напр. — зручніше вранці, трохи хвилююсь...", choose: "Оберіть..." },
      phoneInvalid: "Введіть номер у форматі +380XXXXXXXXX",
      services: ["Безкоштовна консультація", "Косметика / вініри", "Імпланти", "Відбілювання", "Елайнери", "Огляд", "Невідкладна"],
      vias: ["Телефон", "Telegram", "Viber", "WhatsApp"],
      submit: "Надіслати запит →",
      submitting: "Надсилається...",
      successTitle: "Готово!",
      successText: "Зателефонуємо протягом 2 годин.",
      error: "Щось пішло не так. Зателефонуйте напряму.",
      trust: ["Відповідь за 2 години", "Без спаму", "Перший візит безкоштовно"],
    },
  },

  en: {
    navLabels: [
      "01 / INTRO",
      "02 / SERVICES",
      "03 / BEFORE / AFTER",
      "04 / TEAM",
      "05 / REVIEWS",
      "06 / TIKTOK",
      "07 / CLINIC",
      "08 / LOCATION",
      "09 / CONTACT",
    ],
    marquee: [
      "EMERGENCY CARE",
      "COSMETIC DENTISTRY",
      "WHITENING",
      "IMPLANTS",
      "ALIGNERS",
      "VENEERS",
      "ROOT CANALS",
      "ORTHODONTICS",
      "IMPLANTATION",
    ],
    hero: {
      lines: ["YOUR", "SMILE.", "YOUR RULES."],
      sub: "No lectures. No judgement. Just quality care — and genuinely good coffee.",
      cta: "Book for free →",
      stats: [
        ["2400+", "Happy smiles"],
        ["98%", "Come back again"],
        ["4.9", "Google rating"],
      ] as [string, string][],
    },
    services: {
      lines: ["FIX IT.", "ALIGN IT.", "SHINE."],
      sub: "Everything your smile needs — in one place.",
      hint: "Tap a card — see prices",
      toggleOpen: "▲ collapse",
      toggleClosed: "▼ prices",
      panelFoot:
        "The exact cost is confirmed by the doctor at the consultation — it's free",
      list: [
        { num: "01", name: "Veneers", desc: "Artistic restoration and E-max ceramic veneers.", price: "from ₴3,500", items: [
          { name: "Composite veneers (no layering)", price: "₴3,500" },
          { name: "Composite veneers (with layering)", price: "$100" },
          { name: "Ceramic veneers E-max", price: "₴10,500" },
          { name: "Ceramic veneers E-max Premium", price: "₴12,000" },
        ] },
        { num: "02", name: "Prosthetics", desc: "Crowns, dentures, veneers and impressions.", price: "from ₴700", items: [
          { name: "Metal-ceramic crown", price: "₴5,000" },
          { name: "Ceramic crown (zirconia)", price: "₴8,000–10,000" },
          { name: "Ceramic veneer (EMAX)", price: "₴10,500–12,000" },
          { name: "Removable dentures", price: "₴18,000–25,000" },
          { name: "Impressions", price: "₴1,000" },
          { name: "3D scanning", price: "₴2,000" },
          { name: "Model (half jaw)", price: "₴1,000" },
          { name: "Model (full jaw)", price: "₴2,000" },
          { name: "External crown cementation (1 unit)", price: "₴700" },
          { name: "External crown cementation (2 units)", price: "₴1,200" },
          { name: "Crown removal (per unit)", price: "₴700" },
        ] },
        { num: "03", name: "Aligners", desc: "No one will notice. You'll feel it.", price: "from ₴25,000", items: [
          { name: "Aligners (full course)", price: "from ₴25,000" },
          { name: "Braces", price: "from ₴18,000" },
          { name: "Retainers", price: "from ₴2,400" },
        ] },
        { num: "04", name: "Whitening", desc: "Cleaning and whitening — in-office and home options.", price: "from ₴2,000", items: [
          { name: "Professional teeth cleaning", price: "₴2,000–2,500" },
          { name: "Teeth whitening (1 visit)", price: "₴4,000" },
          { name: "Cleaning + whitening combo", price: "₴5,500" },
          { name: "Home whitening trays (2 weeks)", price: "₴7,700" },
          { name: "Home whitening trays (4 weeks)", price: "₴10,400" },
        ] },
        { num: "05", name: "Check-up", desc: "Consultation, anesthesia, fillings, root canals.", price: "from ₴200", items: [
          { name: "Consultation", price: "₴500" },
          { name: "Online consultation", price: "₴500" },
          { name: "Anesthesia", price: "₴200" },
          { name: "Rubber dam", price: "₴200" },
          { name: "Mouth opener (Optragate)", price: "₴200" },
          { name: "Temporary filling", price: "₴300" },
          { name: "Filling (Japan/USA) — medium cavity", price: "₴2,300" },
          { name: "Filling (Japan/USA) — deep cavity", price: "₴2,500" },
          { name: "Root canal treatment (per canal)", price: "₴1,200–1,500" },
          { name: "Emergency pain relief (pulpitis/periodontitis)", price: "₴1,200" },
        ] },
        { num: "06", name: "Urgent", desc: "Broken tooth? Same day.", price: "Call us", items: [
          { name: "Pain exam", price: "Free" },
          { name: "Tooth extraction", price: "from ₴1,200" },
          { name: "Temporary filling", price: "from ₴600" },
        ] },
      ],
    },
    beforeAfter: {
      lines: ["DRAG.", "SEE.", "BELIEVE."],
      sub: "Real before/after. Real patients. Every case is true.",
      casesHint: "cases · drag the slider",
      cases: [
        { treatment: "8 veneers", duration: "2 weeks", before: "Crooked, darkened teeth", after: "Porcelain veneers — natural white" },
        { treatment: "One implant", duration: "3 months", before: "Missing front tooth", after: "Implant with ceramic crown" },
        { treatment: "Zoom whitening", duration: "1 session", before: "Yellow shade", after: "Bright, even tone" },
      ],
    },
    team: {
      eyebrow: "OUR TEAM",
      lines: ["NOT YOUR PARENTS'", "DENTIST."],
      members: [
        { name: "Dr. Chirkova", title: "Dentist · Cosmetic & restorative dentistry", years: 14, yearsLabel: "YEARS OF PRACTICE", bio: "I opened the clinic with one goal: for patients to feel truly heard — not just another tooth on the conveyor. Every smile is a unique story." },
        { name: "Dr. Melnyk", title: "Orthodontist · Aligners & braces", years: 9, yearsLabel: "YEARS OF PRACTICE", bio: "Specializes in orthodontic treatment using modern aligners and digital planning. Over 800 completed orthodontic cases." },
      ],
    },
    reviews: {
      lines: ["THEY SAID IT.", "NOT US."],
      sub: "Real words. No filters.",
      list: [
        { initials: "MV", name: "Maria V.", age: "since 2026", text: "Best clinic in Dnipro! Got veneers done in 2 weeks — the result exceeded all expectations." },
        { initials: "DK", name: "Dmytro K.", age: "since 2026", text: "The doctor is attentive and never rushes. First time I wasn't afraid of going to the dentist!" },
        { initials: "IS", name: "Iryna S.", age: "since 2026", text: "Got an implant — I even forgot where it is. Thank you to the whole team for the care and support!" },
        { initials: "AK", name: "Alina K.", age: "since 2021", text: "Great service — everything fast, painless and no lectures. Now I don't worry about my smile." },
        { initials: "MD", name: "Maksym D.", age: "since 2020", text: "Broke a tooth — it was fixed quickly, neatly and without fuss. Highly recommend." },
        { initials: "OS", name: "Olena S.", age: "since 2022", text: "A crack in my tooth was fixed in a single visit. Now I can even eat nuts again." },
      ],
    },
    tiktok: {
      tt: {
        brand: "TikTok",
        lines: ["WATCH.", "HOW WE", "LIVE."],
        sub: "Real clinic life — no staging, no filters. Follow us.",
        stats: [["6,800+", "Followers"], ["249", "Videos"]] as [string, string][],
        videos: [
          { id: "7643038472294386965", caption: "Half price in Dnipro" },
          { id: "7584496719946173708", caption: "Unhappy patient 😳" },
        ],
      },
      ig: {
        brand: "Instagram",
        lines: ["SUBSCRIBE.", "FOLLOW.", "FEEL IT."],
        sub: "Daily clinic life, results, the team — it's all here.",
        stats: [["6,800+", "Followers"], ["249", "Posts"]] as [string, string][],
        posts: [
          { id: "DWeVhTFDYC3", caption: "Zoom whitening — 8 shades in 1 session ✨" },
          { id: "DYFoSO5tuGD", caption: "Veneers in 2 weeks — custom porcelain 🦷" },
        ],
      },
    },
    clinic: {
      lines: ["A SPACE.", "WHERE YOU'RE", "NOT AFRAID."],
      sub: "Modern equipment. A cozy atmosphere. No stress.",
      videoLabel: "Clinic video",
      stats: [
        { num: "200m²", label: "of modern space" },
        { num: "5", label: "equipped rooms" },
        { num: "2021", label: "year opened" },
      ],
      photos: ["Waiting area", "Room 1", "Room 2", "Sterilization"],
    },
    location: {
      lines: ["FIND US.", "COME IN.", "FEEL IT."],
      sub: "We're in central Dnipro. Metro, parking and coffee after your visit nearby.",
      contacts: [
        { label: "Phone", val: "+38 (099) 31-21-565" },
        { label: "Address", val: "16  Mykhaila Hrushevskoho St, Dnipro" },
        { label: "Hours", val: "Mon–Fri 9:00–20:00 · Sat 12:00–18:00" },
      ],
      reviewsTitle: "GOOGLE REVIEWS",
      googleReviews: [
        { name: "Maria V.", text: "Best clinic in Dnipro! Veneers done in 2 weeks — the result exceeded expectations.", ago: "2 weeks ago" },
        { name: "Dmytro K.", text: "The doctor is attentive and never rushes. First time I wasn't afraid of the dentist!", ago: "1 month ago" },
        { name: "Iryna S.", text: "Got an implant — I even forgot where it is. Thanks to the whole team for the care!", ago: "2 months ago" },
      ],
    },
    contact: {
      lines: ["STOP", "THINKING.", "START."],
      sub: "First consultation is free. Reply within 2 hours.",
      eyebrow: "QUICK REQUEST",
      labels: { name: "Your name", phone: "Phone *", service: "Service", via: "Preferred contact", note: "Note (optional)" },
      placeholders: { name: "Kateryna", phone: "+380 __ ___-__-__", note: "E.g. — mornings are better, a bit nervous...", choose: "Choose..." },
      phoneInvalid: "Enter a number in the format +380XXXXXXXXX",
      services: ["Free consultation", "Cosmetic / veneers", "Implants", "Whitening", "Aligners", "Check-up", "Emergency"],
      vias: ["Phone", "Telegram", "Viber", "WhatsApp"],
      submit: "Send request →",
      submitting: "Sending...",
      successTitle: "Done!",
      successText: "We'll call you within 2 hours.",
      error: "Something went wrong. Please call us directly.",
      trust: ["Reply within 2 hours", "No spam", "First visit free"],
    },
  },
} as const;
